movie_websiteproject/urls.py
from django.contrib import admin
from django.urls import path, include
from movieapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path('', views.home,name="home"),
    path('admin/', admin.site.urls),
    path('signup/',views.signup,name="signup"),
    path('login/',views.user_login,name="login"),
    path('home/',views.home,name="home"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addmovie/',views.addmovie,name="addmovie"),
    path('logout/',views.user_logout,name="logout"),
    path('profile/',views.profile,name="profile"),
    path('search/',include('searchapp.urls')),
]

+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT))

searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),

]

movieapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=70)
    genres = models.CharField(max_length=70)
    year = models.CharField(max_length=70)
    image = models.ImageField(upload_to="movie_image")

    description = models.CharField(max_length=1000, default='about the movie...')
    actors = models.CharField(max_length=100, default='casting')
    youtubelink = models.CharField(max_length=100, default='youtube link here')

    def __str__(self):
        return str(self.pk)


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, default=None)
    rating = models.CharField(max_length=70)
    rated_date = models.DateTimeField(auto_now_add=True)

templates/addmovie.html
{% extends 'base.html' %}
{% block title %}Add Movie{% endblock title %}
{% block css %}
body{
    background: -webkit-linear-gradient(left, #3931af, #00c6ff);
{% endblock css %}
{%block content%}
 {%if perms.movieapp.add_movie%}
<div class="container  mt-2 p-5 mb-2">
<h1 class="text-center text-light">Add Movie</h1>  
  <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for fm in form  %}
        <span class="text-light font-weight-bold">{{fm.label_tag}}</span>
        <p>{{fm}}</p>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Add">
        </form><br>
        {% if messages %}
        {%for msg in messages%}
        {% if msg %}   <div class="alert alert-success">{{msg}}</div>{% endif %}
        {%endfor%}
        {% endif %}
</form>
</div>
{% else %}
<h1 class="text-light mt-2 ml-2">Only Admin has Permission To Add Movie</h1>
{% endif %}
{%endblock content%} 

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>{% block title %}  {% endblock title %}</title>
    <style>{% block css %} {% endblock css %}</style>
  </head>
  <body>
    {% include 'navbar.html' %}
                        {% block content %}



                        {% endblock content %}
      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock title %}
{% block css %}
         body{
                background: -webkit-linear-gradient(left, #3931af, #00c6ff);
            }
          .col-md-3
          {
          display: inline-block;
          margin-left:-4px;
          }

          .carousel-indicators .active {z
          background-color: blue;
            }

          .col-md-3 img{

          width: 170px;
          height: 200px;
          }

          body .carousel-indicator li{
          background-color: blue;
          }

          body .carousel-indicators{
          bottom: 0;
          }

          body .carousel-control-prev-icon,
          body .carousel-control-next-icon{
          background-color: blue;
          }

          .carousel-control-prev,
          .carousel-control-next{
          top: auto;
          bottom: auto;
          padding-top: 222px;
          }
        body .no-padding{
           padding-left: 0,
           padding-right: 0;
           }

        .wrapper{

        margin-bottom:200px;
        }


 {% endblock %}

{% block content %}
<div class="container wrapper">
     {% if messages %}
                {%for msg in messages%}
                {% if msg %}   <div class="alert alert-{{msg.tags}} alert-dismissible fade show font-weight-bold text-primary w-50 ml-3 mt-5">{{msg}} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button></div>{% endif %}
                {%endfor%}
                {% endif %}


    {% for movie, range, nSlides in allMovies %}
    <h5 class="my-4 text-light"><u>{{movie.0.genres}}</u></h5>
<div class="row">
    <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

       {% for i in range %}
      <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" ></li>
      {% endfor %}
    </ul>


    <div class="container carousel-inner no-padding">

      <div class="carousel-item active">
        <div class="col-xs-3 col-sm-3 col-md-3">


          <div class="card" style="width: 18rem">
             <img class="card-img-top" src="{{movie.0.image.url}}"  alt="Card image cap" height="250px" width="200px">    
                      <div class="card-body">
                        <h5 class="card-title">{{movie.0.title}}</h5>
                         <form action="" method="post" class="range-field">
                                                                        {% csrf_token %}  
                                                                        <input type="hidden" name="movieid" value="{{movie.0.id}}"/>
                                                                        <input type="hidden" name="userid" value="{{user.id}}"/> 
                                                                        {{rform.as_p}}
                                                                        <div class="showrating">
                                                                        
                                                                        </div>
                                                                        <input type="submit" class="btn btn-primary" value="Submit">
                        </form>
                      </div>       
                      <div class="card-footer">
                        <small class="text-muted">{{movie.0.genres}}</small>
                        <small class="text-muted">{{movie.0.movieduration}}</small>
                     </div>
          </div>
       </div>


        {% for i in movie|slice:"1:"%}
        <div class="col-xs-3 col-sm-3 col-md-3">
         <div class="card" style="width: 18rem">
             <img class="card-img-top" src="{{i.image.url}}"  alt="Card image cap" height="250px" width="200px">    
                      <div class="card-body">
                        <h5 class="card-title">{{i.title}}</h5>
                         <form action="" method="post" class="range-field">
                                                                        {% csrf_token %}  
                                                                        <input type="hidden" name="movieid" value="{{i.id}}"/>
                                                                        <input type="hidden" name="userid" value="{{user.id}}"/> 
                                                                        {{rform.as_p}}
                                                                        <div class="showrating">
                                                                        
                                                                        </div>
                                                                        <input type="submit" class="btn btn-primary" value="Submit">
                        </form>
                      </div>       
                      <div class="card-footer">
                        <small class="text-muted">{{i.genres}}</small>
                        <small class="text-muted">{{i.movieduration}}</small>
                     </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}

        {% endfor %}
    </div>



</div>
</div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
        </div>
    {% endfor %}
</div>
 {% endblock %}




 

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block css %}
            body{
                background: -webkit-linear-gradient(left, #3931af, #00c6ff);
            }
          .col-md-3
          {
          display: inline-block;
          margin-left:-4px;
          }

          .carousel-indicators .active {
          background-color: blue;
            }

          .col-md-3 img{

          width: 270px;
          height: 300px;
          }

          body .carousel-indicator li{
          background-color: blue;
          }

          body .carousel-indicators{
          bottom: 0;
          }

          body .carousel-control-prev-icon,
          body .carousel-control-next-icon{
          background-color: blue;
          }

          .carousel-control-prev,
          .carousel-control-next{
          top: auto;
          bottom: auto;
          padding-top: 222px;
          }
        body .no-padding{
           padding-left: 0,
           padding-right: 0;
           }

        .wrapper{

        margin-bottom:200px;
        }


 {% endblock %}

{% block content %}
<div class="container wrapper">
{% if  recommended%}
<h5 class="my-4 text-light">Recommended Movie For You</h5>
<div class="row">
{% for item in recommended %}
<div class="col-4 mb-2">
        <div class="card" style="width: 18rem">
                <img class="card-img-top" src="{{item.image}}"  alt="Card image cap" height="350px" width="300px">
                <div class="card-footer">
                <small class="text-muted">{{item.genres}}</small>
                </div>
        </div>
</div>
{% endfor %}
</div>
{% else %}
<h5 class="my-4 text-light">No Recommended Movie Found</h5>
{% endif %}




<br><br>
    <!--Slideshow starts here -->
    {% for movie, range, nSlides in allMovies %}

    <h5 class="my-4 text-light">Filtered By:{{movie.0.genres}}</h5>
<div class="row">
    <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

       {% for i in range %}
      <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" ></li>
      {% endfor %}
    </ul>
    <div class="container carousel-inner no-padding">

      <div class="carousel-item active">
        <div class="col-xs-4 col-sm-3 col-md-3">


          <div class="card" style="width: 25rem">
             <img class="card-img-top" src="{{movie.0.image.url}}"  alt="Card image cap" height="450px" width="350px">
                      <div class="card-body">
                        <h5 class="card-title">{{movie.0.title}}</h5>
                      </div>       
                      <div class="card-footer">
                        <small class="text-muted">{{movie.0.genres}}</small>
                        <small class="text-muted">{{movie.0.movieduration}}</small>
                     </div>
          </div>
       </div>


        {% for i in movie|slice:"1:"%}
        <div class="col-xs-3 col-sm-3 col-md-3">
         <div class="card" style="width: 18rem">
             <img class="card-img-top" src="{{i.image.url}}"  alt="Card image cap" height="350px" width="300px">
                      <div class="card-body">
                        <h5 class="card-title">{{i.title}}</h5>
                      </div>       
                      <div class="card-footer">
                        <small class="text-muted">{{i.genres}}</small>
                        <small class="text-muted">{{i.movieduration}}</small>
                     </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}

        {% endfor %}
    </div>



</div>
</div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
        </div>
    {% endfor %}
</div>
 {% endblock %}




 

templates/logic.html
//if recommended===none
{% for item in movie %}
 <div class="card" style="width: 22rem">
<img class="card-img-top" src="{{item.image.url}}"  alt="Card image cap" height="250px" width="200px">           
<div class="card-footer">
<small class="text-muted">{{item.movieduration}}</small>
</div>
</div>
{%endfor%}









//else if recommended

    {% for item in recommended %}
                                                <div class="col-4 mb-2">
                                                        <div class="card" style="width: 22rem">
                                                            <img class="card-img-top" src="{{item.image}}"  alt="Card image cap" height="250px" width="200px">           
                                                                <div class="card-footer">
                                                                        <small class="text-muted">{{item.genres}}</small>
                                                                        <small class="text-muted">{{item.movieduration}}</small>
                                                                </div>
                                                        </div>
                                                </div>
                    {% endfor %}


//watched movie by user

   <div class="col-12">
                            <h3 class="mb-3 text-light">Watched Movie By {{request.user.username}} </h3>
                        </div>
        <div class="col-12">
            <div id="carouselExampleIndicators3" class="carousel slide" data-interval="8000" data-ride="carousel">

                <div class="carousel-inner">
                  <div class="carousel-item active"> 
                  <div class="row">
                        {% for item in watchedmovie %}
            
                                                <div class="col-4 mb-2">
                                                        <div class="card" style="width: 22rem">
                                                            <img class="card-img-top" src="{{item.movie.image.url}}"  alt="Card image cap" height="250px" width="200px">           
                                                                <div class="card-footer">
                                                                        <small class="text-muted">{{item.movie.genres}}</small>
                                                                        <small class="text-muted">{{item.movie.movieduration}}</small>
                                                                </div>
                                                        </div>
                                                </div>

                          {% endfor %}   
                        </div>
                    </div>



//All Movie list


              {% for item in movie %}
                     
                                                <div class="col-4 mb-2">
                                                        <div class="card" style="width: 22rem">
                                                            <img class="card-img-top" src="{{item.image.url}}"  alt="Card image cap" height="250px" width="200px">           
                                                                <div class="card-footer">
                                                                        <small class="text-muted">{{item.genres}}</small>
                                                                        <small class="text-muted">{{item.movieduration}}</small>
                                                                </div>
                                                        </div>
                                                </div>
               
                          {% endfor %}   
















{% extends 'MovieRecommender/base.html' %}
{% block title %}Home{% endblock title %}
{% block css %}
body{
    background: -webkit-linear-gradient(left, #3931af, #00c6ff);
}
{% endblock css %}
{% block content %}

<section class="pt-5 pb-5">
{% if  request.user.is_authenticated %}
{% if recommended == None %}


{% else %}
 <div class="container">
    <div class="row">
        <div class="col-12">
            <h3 class="mb-3 text-light">Recommended for You </h3>
        </div>
</div>
              
              
{% endif %}

<div class="container">
    {%if watchedmovie == None%}
                        <div class="col-12">
                         <h3 class="mb-3 text-light">You Haven't watched Any Movies</h3>
                        </div>
    {%else%}
</div>                    
{% endif %}
{% else %}
<div class="container">

</div>
  
{% endif %}
</section>
{% endblock content %}
















<section class="pt-5 pb-5">
                {% if messages %}
                {%for msg in messages%}
                {% if msg %}   <div class="alert alert-{{msg.tags}} font-weight-bold text-primary w-50 ml-3">{{msg}}</div>{% endif %}
                {%endfor%}
                {% endif %}
 <div class="container">
    <div class="row">
        <div class="col-6">
            <h3 class="mb-3 text-light">Movie List </h3>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary mb-3 mr-1" href="#carouselExampleIndicators2" role="button" data-slide="prev">
                <i class="fa fa-arrow-left"></i>
            </a>
            <a class="btn btn-primary mb-3 " href="#carouselExampleIndicators2" role="button" data-slide="next">
                <i class="fa fa-arrow-right"></i>
            </a>
        </div>
        <div class="col-12">
            <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">

                <div class="carousel-inner">
                  <div class="carousel-item active"> 
                  <div class="row">
                        {% for item in movie %}
                            {% if forloop.counter <= 6  %}
                                                <div class="col-4 mb-2">
                                                        <div class="card" style="width: 22rem">
                                                            <img class="card-img-top" src="{{item.image.url}}"  alt="Card image cap" height="250px" width="200px">  
                                                                 <div class="card-body">
                                                                        <form action="" method="post" class="range-field">
                                                                        {% csrf_token %}  
                                                                        <input type="hidden" name="movieid" value="{{item.id}}"/>
                                                                        <input type="hidden" name="userid" value="{{user.id}}"/> 
                                                                        {{rform.as_p}}
                                                                        <div class="showrating">
                                                                        
                                                                        </div>
                                                                        <input type="submit" class="btn btn-primary" value="Submit">
                                                                        </form>
                                                                </div>         
                                                                <div class="card-footer">
                                                                        <small class="text-muted">{{item.genres}}</small>
                                                                        <small class="text-muted">{{item.movieduration}}</small>
                                                                </div>
                                                        </div>
                                                </div>
                            {% endif %}
                          {% endfor %}   
                        </div>
                    </div>


            <div class="carousel-item"> 
                  <div class="row">
                        {% for item in movie %}
                            {% if forloop.counter >= 6 and forloop.counter <= 12%}
                                                <div class="col-4 mb-2">
                                                        <div class="card" style="width: 22rem">
                                                            <img class="card-img-top" src="{{item.image.url}}"  alt="Card image cap"}>    
                                                                <div class="card-body">
                                                                        <form action="" method="post" class="range-field">
                                                                        {% csrf_token %}  
                                                                        <input type="hidden" name="movieid" value="{{item.id}}"/>
                                                                        <input type="hidden" name="userid" value="{{user.id}}"/> 
                                                                        {{rform.as_p}}
                                                                        <div class="showrating">
                                                                        
                                                                        </div>
                                                                        <input type="submit" class="btn btn-primary" value="Submit">
                                                                        </form>
                                                                </div>        
                                                                <div class="card-footer">
                                                                        <small class="text-muted">{{item.genres}}</small>
                                                                        <small class="text-muted">{{item.movieduration}}</small>
                                                                </div>
                                                        </div>
                                                </div>
                            {% endif %}
                          {% endfor %}   
                        </div>
                    </div>
                       
                       
                           
                      
                </div>
            </div>
        </div>
    </div>
</div>
</section>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}
{% block css %}
body{
    background: -webkit-linear-gradient(left, #3931af, #00c6ff);
}
{% endblock css %}
{% block content %}
<div class="container p-5 mb-5">
<form action="" method="post" novalidate>
{% csrf_token %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">{{error}}</div>
{% endfor %}
{% endif %} <br>
{% for fm in  form %}
<span class="text-light">{{fm.label_tag}}</span>
<p>
{{fm}}
</p>
{% if fm.errors  %}
<div class="alert alert-danger">
{{fm.errors|striptags}}
</div>
{% endif %}
{% endfor %} <br>
<input type="submit" value="Login" class="btn btn-primary"><br>
</form>
</div>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary" >


  <a class="navbar-brand" href="{% url 'home' %}">Movie Recommender</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      {% if  request.user.is_authenticated %}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'addmovie' %}">Add Movie</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>

        <form class="d-flex"  action="{% url 'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="text" placeholder="Search" name="q" aria-label="Search">
        <button  class="btn btn-outline-success" type="button"><i class="fa fa-search"></i></button>
      </form>

      {% endif %}
      {%if not request.user.is_authenticated%}
       <li class="nav-item">
        <a class="nav-link" href="{% url 'signup' %}">Signup</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="{%url 'login'%}">Login</a>
      </li>
      {%endif%}
   
    </ul>
  </div>
</nav>

<nav class="navbar fixed-bottom navbar-expand-sm navbar-light bg-primary">

<span class="text-light font-weight-bold">&copy All Right Reserved 2019-2020</span>


    
</nav>

templates/search.html
{% extends 'base.html'  %}
{% load static %}
{% block metadescription %}
We have variety of products for your daily needs
{% endblock %}


{% block title %}
Search
{% endblock %}


{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b>"{{query}}"</b></p>
</div>



<div class="container">
   <div class="row mx_auto">
       {% for title in title %}

            <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4">
                <div class="card-body" style="width: 250px; height: 150px;">
                        <h4>{{title.title}}</h4>

                    </div>

                <div class="card text-center" style="min-width:18rem;" >
                    <a href="{{request.user.get_url}}"> <img class="card-img-top my_image" src="{{title.image.url}}"  alt="{{title.title}}" width="100px" height="300px" > </a>


                </div>
           </div>
   </div>

                {% empty %}
                <div class="row mx-auto">
                    <p class="text-center my_search_text">0 result found</p>
       {% endfor %}
                </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block title %}Signup{% endblock title %}
{% block css %}
body{
    background: -webkit-linear-gradient(left, #C0C0C0, #EAECEE);
}
.wrapper{
        margin-bottom:200px;
}

{% endblock css %}
{% block content %}

<div class="container p-5 mb-5 wrapper">
     {% if messages %}
                {%for msg in messages%}
                {% if msg %}   <div class="alert alert-{{msg.tags}} alert-dismissible fade show font-weight-bold text-primary w-50 ml-3 mt-5">{{msg}} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button></div>{% endif %}
        {%endfor%}
        {% endif %}

<form action="" method="post" novalidate>
{% csrf_token %}
{% for fm in form %}
<span class="text-light">{{fm.label_tag}}</span>
<div class="form-group">
{{fm}}
</div>
{% if fm.errors %}
<div class="alert alert-danger lert-dismissible fade show">
{{fm.errors|striptags}}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>

</div>
{% endif %}
{% endfor %}<br/>
  <input type="submit" value="submit" class="btn btn-primary">
</form>
</div>
{% endblock content %}